// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMA05ghqlc-rp-7aTBdjW8bN2D7l9M6aw',
    appId: '1:182901889421:web:b7adaf9a86482a7fe2c5c4',
    messagingSenderId: '182901889421',
    projectId: 'atividade-6--pokedex',
    authDomain: 'atividade-6--pokedex.firebaseapp.com',
    storageBucket: 'atividade-6--pokedex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEQizQ-tEMEvKghq9Ok505FMRFjS6ITs',
    appId: '1:182901889421:android:0a171954dc404ea3e2c5c4',
    messagingSenderId: '182901889421',
    projectId: 'atividade-6--pokedex',
    storageBucket: 'atividade-6--pokedex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpueMsmGkcEAhZ3Gtxu_RadbXWad5WcCw',
    appId: '1:182901889421:ios:d9fd3c1e95d0c6d1e2c5c4',
    messagingSenderId: '182901889421',
    projectId: 'atividade-6--pokedex',
    storageBucket: 'atividade-6--pokedex.firebasestorage.app',
    iosBundleId: 'com.example.pokedexApp',
  );
}
